### ISSUE TITLE
Allow users to follow other users.

### ISSUE THREAD

**Issue by marc9622** [ITU-BDSA23-GROUP13/Chirp#126]
Acceptance Criteria:
- [x] Add Database support. #125
- [x] Add Razor Pages Backend support. #124
- [x] Add UI frontend support. #123

**Comment by copeitu** [comment]
#111
